modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.


license="${mod_license}"


[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
issueTrackerURL="https://github.com/YeetmanLord/So-Many-Enchants/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enchants"
logoFile="icon.png" #optional
credits="NeoForge for creating the resources to code this mod" #optional
authors="${mod_authors}" #optional
description='''
Adds a wide variety of new enchantments to 
the game.

Yay finally in full release!
'''

[[dependencies.so_many_enchants]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"


[[dependencies.so_many_enchants]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
